# Generated by Django 5.2.8 on 2025-11-09 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_features_and_itemcategory'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='item',
            name='core_item_room_id_4d52b1_idx',
        ),
        migrations.RenameIndex(
            model_name='item',
            new_name='core_item_status_afb428_idx',
            old_name='core_item_status_idx',
        ),
    ]
