# Generated by Django 5.2.8 on 2025-11-09 02:15

import django.contrib.postgres.constraints
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_item_core_item_room_id_4d52b1_idx_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='appointment',
            name='appointment_end_after_start',
        ),
        migrations.RemoveConstraint(
            model_name='appointment',
            name='exclude_overlap_per_item',
        ),
        migrations.RemoveConstraint(
            model_name='request',
            name='request_date_end_after_date_start',
        ),
        migrations.RemoveIndex(
            model_name='appointment',
            name='core_appoin_time_ra_2769e4_gist',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='time_range',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='end_at',
            field=models.DateField(help_text='Data de sfârșit (zi întreagă)'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='start_at',
            field=models.DateField(help_text='Data de început (zi întreagă)'),
        ),
        migrations.AlterField(
            model_name='request',
            name='date_end',
            field=models.DateField(help_text='Data de sfârșit (zi întreagă)'),
        ),
        migrations.AlterField(
            model_name='request',
            name='date_start',
            field=models.DateField(help_text='Data de început (zi întreagă)'),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.CheckConstraint(condition=models.Q(('end_at__gte', models.F('start_at'))), name='appointment_end_after_or_equal_start'),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(expressions=[('item', '='), ('start_at', '=')], name='exclude_overlap_per_item_per_date'),
        ),
        migrations.AddConstraint(
            model_name='request',
            constraint=models.CheckConstraint(condition=models.Q(('date_end__gte', models.F('date_start'))), name='request_date_end_after_or_equal_date_start'),
        ),
    ]
