# Generated by Django 5.2.8 on 2025-11-09 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_change_datetime_to_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='request',
        ),
    ]
