import type { Metadata } from "next";
import "./globals.css";
import Navigation from "./componente/Navigation";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={``}>
        <Navigation />
        <div className=" pt-20">{children}</div>
      </body>
    </html>
  );
}
