# Generated by Django 5.2.8 on 2025-11-08 12:08

import django.contrib.auth.models
import django.contrib.auth.validators
import django.contrib.postgres.fields.ranges
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RenameIndex(
            model_name='appointment',
            new_name='core_appoin_item_id_077209_idx',
            old_name='core_appointment_item_start_idx',
        ),
        migrations.RenameIndex(
            model_name='appointment',
            new_name='core_appoin_time_ra_2769e4_gist',
            old_name='core_appointment_time_range_gist_idx',
        ),
        migrations.RenameIndex(
            model_name='item',
            new_name='core_item_room_id_4d52b1_idx',
            old_name='core_item_room_status_idx',
        ),
        migrations.RenameIndex(
            model_name='request',
            new_name='core_reques_status_41ef2c_idx',
            old_name='core_request_status_created_idx',
        ),
        migrations.RenameIndex(
            model_name='room',
            new_name='core_room_is_acti_9de2db_idx',
            old_name='core_room_is_active_idx',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time_range',
            field=django.contrib.postgres.fields.ranges.DateTimeRangeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('is_superuser', True)), fields=('is_superuser',), name='unique_single_superadmin'),
        ),
    ]
