# Generated by Django 5.2.8 on 2025-11-08 14:23

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_required_days_per_week', models.PositiveSmallIntegerField(default=2, help_text='Numărul default de zile obligatorii de prezență fizică pe săptămână')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Organizational Policy',
                'verbose_name_plural': 'Organizational Policies',
                'db_table': 'core_org_policy',
            },
        ),
        migrations.AddField(
            model_name='team',
            name='required_days_per_week',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Numărul de zile obligatorii de prezență fizică pe săptămână pentru această echipă. Dacă este None, se folosește default-ul organizațional.', null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='required_weekdays',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, help_text='Lista opțională cu zilele din săptămână când angajații trebuie să fie prezenți. 0=Luni, 1=Marți, ..., 6=Duminică. Dacă este None, nu există restricții pe zile specifice.', null=True, size=None),
        ),
    ]
