# Generated by Django 5.2.8 on 2025-11-08 15:06

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailOutbox',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('to', models.EmailField(help_text='Adresa de email destinatar', max_length=254)),
                ('template', models.CharField(help_text="Numele template-ului (ex: 'appointment_summary')", max_length=64)),
                ('locale', models.CharField(default='ro', help_text="Limba pentru template (ex: 'ro', 'en')", max_length=8)),
                ('context', models.JSONField(default=dict)),
                ('idempotency_key', models.CharField(db_index=True, help_text='Cheie unică pentru a preveni trimiterea duplicată', max_length=64, unique=True)),
                ('scheduled_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Când ar trebui trimis email-ul')),
                ('attempts', models.PositiveSmallIntegerField(default=0, help_text='Numărul de încercări de trimitere')),
                ('locked_at', models.DateTimeField(blank=True, help_text='Când a fost blocat pentru procesare (pentru a evita procesarea paralelă)', null=True)),
                ('sent_at', models.DateTimeField(blank=True, help_text='Când a fost trimis cu succes (null = încă neprocesat)', null=True)),
                ('error', models.TextField(blank=True, default='', help_text='Mesaj de eroare dacă trimiterea a eșuat')),
            ],
            options={
                'verbose_name': 'Email Outbox',
                'verbose_name_plural': 'Email Outbox',
                'db_table': 'notify_email_outbox',
                'ordering': ['scheduled_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='EmailDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_message_id', models.CharField(blank=True, default='', help_text='ID-ul mesajului de la provider (ex: SendGrid message_id)', max_length=128)),
                ('status', models.CharField(default='SENT', help_text='Status: SENT sau FAILED', max_length=16)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('outbox', models.OneToOneField(help_text='Mesajul din outbox pentru care este această livrare', on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to='notify.emailoutbox')),
            ],
            options={
                'verbose_name': 'Email Delivery',
                'verbose_name_plural': 'Email Deliveries',
                'db_table': 'notify_email_delivery',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('APPOINTMENT_SUMMARY', 'Appointment summary'), ('REQUEST_STATUS', 'Request status changed'), ('DESK_RELEASE_ASK', 'Ask to release desk')], max_length=64)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('payload', models.JSONField(default=dict)),
                ('actor', models.ForeignKey(blank=True, help_text='Utilizatorul care a declanșat evenimentul', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events_actor', to=settings.AUTH_USER_MODEL)),
                ('subject_user', models.ForeignKey(blank=True, help_text='Utilizatorul pentru care este notificarea', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events_subject', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Event',
                'verbose_name_plural': 'Notification Events',
                'db_table': 'notify_notification_event',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='emailoutbox',
            name='event',
            field=models.ForeignKey(help_text='Evenimentul care a generat acest email', on_delete=django.db.models.deletion.CASCADE, related_name='outbox', to='notify.notificationevent'),
        ),
        migrations.CreateModel(
            name='UserEmailPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_summary', models.BooleanField(default=True, help_text='Primește email când creează o programare?')),
                ('request_status', models.BooleanField(default=True, help_text='Primește email când se schimbă statusul unei cereri?')),
                ('desk_release_ask', models.BooleanField(default=True, help_text='Primește email când i se cere să elibereze biroul?')),
                ('frequency', models.CharField(choices=[('instant', 'Instant'), ('daily', 'Daily digest')], default='instant', help_text='Frecvența notificărilor', max_length=16)),
                ('user', models.OneToOneField(help_text='Utilizatorul pentru care sunt aceste preferințe', on_delete=django.db.models.deletion.CASCADE, related_name='email_prefs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Email Preference',
                'verbose_name_plural': 'User Email Preferences',
                'db_table': 'notify_user_email_preference',
            },
        ),
        migrations.AddIndex(
            model_name='notificationevent',
            index=models.Index(fields=['type', 'created_at'], name='notify_noti_type_01f415_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationevent',
            index=models.Index(fields=['subject_user', 'created_at'], name='notify_noti_subject_9c17bd_idx'),
        ),
        migrations.AddIndex(
            model_name='emailoutbox',
            index=models.Index(fields=['sent_at', 'scheduled_at'], name='notify_emai_sent_at_307a25_idx'),
        ),
        migrations.AddIndex(
            model_name='emailoutbox',
            index=models.Index(fields=['idempotency_key'], name='notify_emai_idempot_ff1d5b_idx'),
        ),
    ]
